### PR TITLE
Use s3 head instead of get to retrieve item metadata

### PR DESCRIPTION
**Pull request by EngHabu**
Doing container.Item(id) shouldn't send a GetObject request because that actually gets the object bytes and for large objects that might not be the desired behavior.
I changed container.Item(id) to send a HeadObject request instead. It'll still retrieve the same set of properties/metadata it used to.
item.Open() sends a separate Get request anyway to retrieve the io.ReaderCloser which will continue to be the case.

### CODE REVIEW

**Comment by EngHabu** [comment]
CC @jsteenb2 @Pisush Can you help with the failures? I don't have access to jenkins to see what is failing... and running unit tests in GoLand passes

**Comment by tamalsaha** [comment]
Dup https://github.com/graymeta/stow/pull/160 ?

**Comment by EngHabu** [comment]
Ref: https://github.com/graymeta/stow/issues/181

**Comment by johnmotz** [comment]
Will have someone on the team review the PR tomorrow

**Comment by EngHabu** [comment]
Thanks @johnmotz!

**Comment by EngHabu** [comment]
Maybe today @johnmotz?

**Comment by jsteenb2** [comment]
hey @EngHabu, thanks for contributing! We have a dependency issue in jenkins that breaking the build. If you can clean up the dependencies we should be good to go once the jenkins build/test pass 👍 

```
dep ensure
Warning: the following project(s) have [[constraint]] stanzas in Gopkg.toml:

  ✗  github.com/Azure/go-autorest

However, these projects are not direct dependencies of the current project:
they are not imported in any .go files, nor are they in the 'required' list in
Gopkg.toml. Dep only applies [[constraint]] rules to direct dependencies, so
these rules will have no effect.

Either import/require packages from these projects so that they become direct
dependencies, or convert each [[constraint]] to an [[override]] to enforce rules
on these projects, if they happen to be transitive dependencies.

grouped write of manifest, lock and vendor: scratch directory /mnt/src/github.com/graymeta/stow/.vendor-new already exists, please remove it
make: *** [deps] Error 1
make: *** [runcontainer] Error 2
```

**Comment by EngHabu** [comment]
💨

**Pull request merged**
